version: "3"
services:
  nodeserver:
    build:
      context: ./
    expose:
      - 8000
    depends_on:
      - database
  database:
    image: mysql
    hostname: database
    env_file:
      - ./.env
 
